/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:                  '#f8f9ff',
        surface:                     '#f8f9ff',
        'surface-bright':            '#f8f9ff',
        'surface-dim':               '#cbdbf5',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#eff4ff',
        'surface-container':         '#e5eeff',
        'surface-container-high':    '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface':                '#0b1c30',
        'on-surface-variant':        '#464555',
        'inverse-surface':           '#213145',
        'inverse-on-surface':        '#eaf1ff',
        outline:                     '#777587',
        'outline-variant':           '#c7c4d8',
        'surface-tint':              '#4d44e3',
        primary:                     '#3525cd',
        'on-primary':                '#ffffff',
        'primary-container':         '#4f46e5',
        'on-primary-container':      '#dad7ff',
        'inverse-primary':           '#c3c0ff',
        secondary:                   '#006591',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#39b8fd',
        'on-secondary-container':    '#004666',
        tertiary:                    '#005338',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#006e4b',
        'on-tertiary-container':     '#67f4b7',
        error:                       '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'primary-fixed':             '#e2dfff',
        'primary-fixed-dim':         '#c3c0ff',
        'on-primary-fixed':          '#0f0069',
        'secondary-fixed':           '#c9e6ff',
        'secondary-fixed-dim':       '#89ceff',
        'on-secondary-fixed':        '#001e2f',
        'tertiary-fixed':            '#6ffbbe',
        'tertiary-fixed-dim':        '#4edea3',
        'on-tertiary-fixed':         '#002113',
        'surface-variant':           '#d3e4fe',
      },
      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
        pulseDot: {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.4' },
        },
        spin: {
          from: { transform: 'rotate(0deg)' },
          to:   { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'fade-up':   'fadeUp 0.5s ease both',
        float:       'float 4s ease-in-out infinite',
        'pulse-dot': 'pulseDot 1.5s ease-in-out infinite',
        spin:        'spin 1s linear infinite',
      },
    },
  },
  plugins: [],
}
